### ISSUE TITLE
Please rebalance the gold rings, some items are not worth adding

### ISSUE THREAD

**Issue by Bksp** [Additional-Mods/additionaladditions#101]
![1](https://user-images.githubusercontent.com/47306658/212524294-2fa2332d-1bdc-494e-ab53-df292dec0638.png)
![2](https://user-images.githubusercontent.com/47306658/212524299-3f622aa5-b4fe-4cba-8021-d01c3ddad3ed.png)

_personally it would improve the damage stats and armor resistance very little, a 0.5+_

**Comment by Dqu1J** [comment]
sorry, that won't change. you can however modify the stats yourselfs using a data pack. see wiki for info

**Comment by Bksp** [comment]
thanks, i already did it
