### ISSUE TITLE
Request for values to be put in config

### ISSUE THREAD

**Issue by bones-01** [Additional-Mods/additionaladditions#105]
I really want to be able to tweak down the rose gold tools a little bit, it feels a bit unbalanced that they have the same digging speed as netherite for such an inexpensive tool.  If you could put that into the config so I can tweak it down to 7 I'd appreciate it.

I'd like to see the food values in the configs possibly.  Reason being, I'd like it if the honeyed apples were 6 hunger and 2.2 or 2.3 saturation factor, making them slightly worse golden carrots but still more saturation than steaks.  Making them a bit better than steak will at least give me a reason to go for bees earlier which I think is really fun, but then I don't have to enforce this on anybody as I can just put it in my own configs.  This one I am less invested in.

Thanks!

**Comment by Dqu1J** [comment]
already exists!
https://github.com/Additional-Mods/additionaladditions/wiki/Datapack-Behaviours

**Comment by bones-01** [comment]
Oh my goodness I had no idea, thank you for letting me know!

**Comment by Dqu1J** [comment]
np!
