### ISSUE TITLE
Can't upgrade with Rose Gold Alloy 1.19.4 with 1.20 features

### ISSUE THREAD

**Issue by Venaf** [Additional-Mods/additionaladditions#109]
When trying to use a smithing table to upgrade, I can't move either the weapon or the alloy into the table.  I think this is because there's no smithing template for it.  Specifically, I'm using the 1.20 features datapack built into minecraft.

When doing the same without the 1.20 features, I can upgrade as expected, no issues with the smithing table.

While I realize this might not be an issue right now, I figured it would be good to bring up so that you can prepare your plan for it if you haven't yet.

**Comment by Dqu1J** [comment]
1.20 is not supported yet
