### ISSUE TITLE
Crashing bedrock players using geyser

### ISSUE THREAD

**Issue by snkiz** [Additional-Mods/additionaladditions#110]
I have a server running geyser to connect bedrock players. When they open crafting they crash with additional additions installed.
This post had a similar issue. It ended up being an item tag mismatch. https://github.com/GeyserMC/Geyser/issues/3549

**Comment by Mira047** [comment]
could you explain this whole thing... in the first place?

since yk additional additions is a java mod, and shouldnt even work on bedrock in the first place, nor give support for it

**Comment by snkiz** [comment]
Geyser is a plugin to translate bedrock to java servers. It does have it's limitations, but other mods I have that add items don't seem to cause problems. Bedrock and vanilla clients just don't have them. The problem is as I stated, and similar to the issue I linked. What tipped me off specifically was this post https://github.com/GeyserMC/Geyser/issues/3549#issuecomment-1483160591 The mod in question adds items and achievements. It was a typo that java ignored but  bedrock did not. 
I can't be sure, there's to much to go over for me. But I think there is a mismatch between the achievements and items, a spelling mistake or something. like the issue I linked to. 
I understand this is a little outside normal support. But on the surface it appears it's only a small thing holding this back. I do miss my glo sticks.

**Comment by vico93** [comment]
I dont know if is possible to use this mod on Geyser since it adds items and entities, what requires the client to also have the mod, what isnt possible with Bedrock, of course. Geyser only works with mods that allow vanilla clients to join the server

**Comment by snkiz** [comment]
Geyser's wiki says that if a server can connect to vanilla Java clients then it should work. I was using AA on my server and my client.  I've checked it myself  my vanilla java clients don't  crash when they don't have the mod, they just don't get the items. if it isn't possible to just be benign to geyer I understand. But it doesn't seem like that should be the case, only that it is. So instead of saying what I already know, that it doesn't work on bedrock. Ask why is it doing this when there shouldn't be any reason for it.

**Comment by Dqu1J** [comment]
geyser is not supported as additional additions has to be installed on the client too

**Comment by snkiz** [comment]
> geyser is not supported as additional additions has to be installed on the client too

I understand it does if you want to use it. But if it doesn't crash java clients who don't have it when the server does, there's no reason fo it to happen to geyer clients. I don't want you to support geyer. Just fix whatever error is getting in the way. look it's your project you do you but it seems like you are just giving me this boilerplate response without reading the posts. I am not asking for geyser support any more than vanilla is supported. As in don't kill the clients game if they are missing the mod.

**Comment by Mira047** [comment]
Your point is invalidating itself. You yourself said it works on a vanilla java client, no? It specifically doesn't work on bedrock which is literally geyser support

**Comment by snkiz** [comment]
No what I'm trying to do is have the server mod not crash their client when they don't have the mod. Not give them the mod. When I say vanilla I mean un-modded mojang client. In short your mod out of the 50 or so on my server is the only one that that has a problem with a client that doesn't have the mod. It's strange that it only appears with a geyser client Again geyer is emulating an unmodded vanilla client, the server isn't seeing a bedrock client, or a geyser client. The server thinks it's a stock minecraft client. Those work when AA is present on the server but not the client. Maybe geyser is stricter with error handling, IDK. Or maybe since they've marked a similar issue as fixed, you have a typo that one day is going to crop up. I don't know how to be more clear.
