### ISSUE TITLE
Pocket Jukebox not working with URL Music Discs

### ISSUE THREAD

**Issue by hyperdotbat** [Additional-Mods/additionaladditions#127]
Not sure on which part the issue is underlying, but sadly the Pocket Jukebox doesnt work with [https://modrinth.com/mod/url-music-discs](https://modrinth.com/mod/url-music-discs). It does accept the disc, but sadly does not play it.
If its not on your side; sorry for false report

**Comment by neonishere** [comment]
Same problem with the Etched mod (https://www.curseforge.com/minecraft/mc-mods/etched), except it doesn't even accept the disc

**Comment by neonishere** [comment]
@hyperdotbat if you still need it, the etched mod has a boombox item, which basically does the same thing as pocket jukebox, except it also accepts it's own mod's url discs
