### ISSUE TITLE
Scoped Crossbow buggy in third person

### ISSUE THREAD

**Issue by LocoPineapples** [Additional-Mods/additionaladditions#39]
If you try to sneak and use the the scope in third person, the spyglass hud overlay begins rapidly flashing and bugging out until you let go. The normal spyglass still doesn't affect anything in third person, just the crossbow version.

**Comment by LocoPineapples** [comment]
Forge 40.0.41 for Minecraft 1.18.2. AdAd is V. 3.0.1.1.
[latest.log](https://github.com/Dqu1J/additionaladditions/files/8476109/latest.log)

**Comment by Dqu1J** [comment]
fixed in 4.0.0
