### ISSUE TITLE
Some fun and useful suggestions

### ISSUE THREAD

**Issue by Meskino** [Additional-Mods/additionaladditions#49]
Well, without further ado, here are my suggestions:

wooden step ladder: basically a portable ladder where any biped mob (like illagers) can climb it  and the endermans can steal it.

miner's chisel: you can chisel stone-like blocks for climbing as a ladder and prospecting for ore veins through advancement pop-ups with the deposit coords. 

pogo stick: a new vehicle that can be used to transport yourself by jumping while holding it in your hand and bouncing over mobs so funny.

copper pipeworks: can be used to irrigate crops, transport potion effects (splash & lingering types) and lastly carry lightning bolts if these pipes are connected to a lighting rod; not to expand too much, the lighting bolts should be ejected from the pipes in particles (with a new texture perhaps) because horizontal lighting bolts isn't implemented in the game as far as I know.

well, these are my suggestions. thanks for reading and sorry for my English.

**Comment by Dqu1J** [comment]
Thanks for your suggestions! I will consider them and write them down, but I'll be closing this issue right now.
