### ISSUE TITLE
Rose gold crash following update

### ISSUE THREAD

**Issue by IcestarLoki** [Additional-Mods/additionaladditions#51]
After updating Additional Additions from version 3.0.1 to version 4.0.0, any time I try to use a rose gold axe to chop wood, both client and server crash. It was working fine before the update.

crash report:
[crash-2022-05-10_15.18.28-client.txt](https://github.com/Additional-Mods/additionaladditions/files/8664432/crash-2022-05-10_15.18.28-client.txt)

**Comment by Dqu1J** [comment]
Unable to reproduce on both 1.18.2 and 1.18.1

**Comment by Dqu1J** [comment]
Please update to 1.18.2, 1.18.1 is not being supported. Thanks for reporting this however, I marked 1.18.1 as unsupported on curseforge & modrinth.
