### ISSUE TITLE
Boots only accept unbreaking when enchanted with speed

### ISSUE THREAD

**Issue by Dqu1J** [Additional-Mods/additionaladditions#52]

**Comment by foul-fortune-feline** [comment]
I fixed this in my 1.19 port fyi, but it obvi changes a lot more than that code-wise

**Comment by foul-fortune-feline** [comment]
The issue is simply that you're missing a not symbol in the check for enchantment compatibility

**Comment by foul-fortune-feline** [comment]
iirc, it checks to see if speed is enabled, and if so returns false
