### ISSUE TITLE
[Feature] es_es translation

### ISSUE THREAD

**Issue by kxkxrxtx** [Additional-Mods/additionaladditions#64]
I full translated the mod for es_es users! I've got some liberties translating some advancements, as it's difficult to translate sland directly (for the watering can and nugget ones), but I think is vewry polished. And sorry but I have no clue how to open a PR u_u

Here you have!
[es_es.txt](https://github.com/Additional-Mods/additionaladditions/files/8840156/es_es.txt)
(sorry for the edits "n_n)

**Comment by Dqu1J** [comment]
Thank you! I'll work on adding those in the next few days

**Comment by Dqu1J** [comment]
Added

**Comment by Dqu1J** [comment]
(I'll put you in the credits once the release drops)

**Comment by kxkxrxtx** [comment]
I'm glad to help n_n
