### ISSUE TITLE
Can't Change Crossbow Zoom Keybind

### ISSUE THREAD

**Issue by ardissaps** [Additional-Mods/additionaladditions#65]

**Comment by Dqu1J** [comment]
That is intended

**Comment by ardissaps** [comment]
> That is intended

Oh sorry, how about right shif as an addition to zoom in crossbow, my left shift broken (remapped with macro G Key next to it but can only right shift)

**Comment by Dqu1J** [comment]
It should still work I think. You need to crouch, not press left shift specifically

**Comment by ardissaps** [comment]
> It should still work I think. You need to crouch, not press left shift specifically

thank you very much! will try soon
