### ISSUE TITLE
Add Rosegold Equipment material from Rosegold ingot from MCA

### ISSUE THREAD

**Issue by ardissaps** [Additional-Mods/additionaladditions#66]
MCA add item Rose Gold Ingot, would you add their ingot as recipe to make your armor rose gold (in addition to copper ingot)? thx in advance

https://imgur.com/a/aAifiRv

**Comment by xHqrley** [comment]
You can do this yourself with a datapack, so I don't know why you are requesting this here.

**Comment by ardissaps** [comment]
> You can do this yourself with a datapack, so I don't know why you are requesting this here.

I don't know exactly how, but thx anyway for the mod.

**Comment by xHqrley** [comment]
If you give me a direct way of contacting you (Discord, email, etc) I'd just need a couple pieces of information and I could make that for you if you want. My Discord is Hxrl#5744 if you would like to use that means.

**Comment by Dqu1J** [comment]
Yeah, you can do it via a datapack, no need for adding it on mod side.
