### ISSUE TITLE
Crashes When Throwing Glowstick

### ISSUE THREAD

**Issue by roninvanderwerke** [Additional-Mods/additionaladditions#74]
Using version 5.0.1 my client crashes when throwing glowsticks (especially when throwing them far away or really close)

I'm also using these mods if that helps:
Adorn-3.5.4+1.19-fabric.jar
advancementinfo-1.19-fabric0.53.3-1.3.1.jar
alternate-current-mc1.19-1.4.0.jar
animatica-0.5+1.19.jar
antighost-1.19-fabric0.55.3-1.1.5.jar
appleskin-fabric-mc1.19-2.4.0.jar
architectury-5.7.28-fabric.jar
autopath-mc1.19-1.4.9.jar
AxesAreWeapons-1.5.2-fabric-1.17.1.jar
bedrockify-1.4.2+mc1.19.jar
beenfo-1.19-fabric0.53.3-1.3.3-spigot.jar
BetterF3-1.3.1-Fabric-1.19.jar
bettermounthud-1.1.4.jar
blur-2.6.0.jar
borderless-mining-1.1.4+1.19.jar
brb-1.6.0-fabric.jar
c2me-fabric-mc1.19-0.2.0+alpha.8.2.jar
carpet-extra-1.19-1.4.79.jar
cem-0.7.1.jar
charm-fabric-1.19-4.1.2.jar
charmonium-fabric-1.19-4.1.0.jar
chesttracker-1.19-1.1.17.jar
Chunky-1.2.217.jar
CITResewn-1.1.1+1.19.jar
ClearDespawn-fabric-1.19-1.1.8.jar
clickthrough-1.19-fabric0.53.3-0.4.jar
cloth-config-7.0.72-fabric.jar
colormatic-3.1.2+mc.1.19.jar
continuity-2.0.0+1.19.jar
cullleaves-2.3.4.jar
dashloader-4.0.0+1.19.jar
DCCH-2.0+1.17.jar
deathlog-0.2.10+1.19.jar
debugify-2.2.0-fabric-1.19.jar
DetailArmorBar-2.6.2+1.19-fabric.jar
dynamic-fps-2.2.0.jar
easiercrafting-1.19-fabric0.53.3-1.7.jar
fabric-api-0.57.0+1.19.jar
fabric-carpet-1.19-1.4.79+v220607.jar
fabric-language-kotlin-1.8.1+kotlin.1.7.0.jar
sodium-fabric-mc1.19-0.4.2+build.16.jar

**Comment by roninvanderwerke** [comment]
Okay I removed some mods and now it works like a charm! (I think dashloader was the cause, as it has given me problems in the past)

**Comment by Dqu1J** [comment]
Do you have a crash report?

**Comment by Dqu1J** [comment]
No reply in nearly 30 days, closing
