### ISSUE TITLE
Some recipes are missing

### ISSUE THREAD

**Issue by calloatti** [Additional-Mods/additionaladditions#76]
Test scenario:

**Minecraft:** 1.18.2  
**Loader:** [FABRIC 0.14.8](https://fabricmc.net)  
  
**Mods**  
- 001 [Additional Additions | Fabric: AdditionalAdditions-4.0.5.jar](https://www.curseforge.com/minecraft/mc-mods/additional-additions) (1.18.2)  
- 002 [Roughly Enough Items Fabric/Forge (REI): RoughlyEnoughItems-8.3.510.jar](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) (1.18.2)  
  
**APIs/LIBs**  
- 003 [Architectury API (Fabric/Forge): architectury-4.6.77-fabric.jar](https://www.curseforge.com/minecraft/mc-mods/architectury-api) (1.18.2)  
- 004 [Cloth Config API (Fabric/Forge): cloth-config-6.2.62-fabric.jar](https://www.curseforge.com/minecraft/mc-mods/cloth-config) (1.18.2)  
- 005 [Fabric API: fabric-api-0.58.0+1.18.2.jar](https://www.curseforge.com/minecraft/mc-mods/fabric-api) (1.18.2)  
  
Missing recipes:

Trident Shard
Depth Meter
Gold Ring

Checking the jar file, confirmed that those are missing in data\additionaladditions\recipes

**Comment by calloatti** [comment]
Should have read the wiki first. Only the Depth Meter recipe is missing, since the other 2 are drops/trade items.

**Comment by Dqu1J** [comment]
Send your config file

**Comment by calloatti** [comment]
This is it: https://paste.ee/p/FKtDl

The config is the default one, to be sure I deleted everything in the config folder and restarted MC, still missing the depth meter recipe.

**Comment by calloatti** [comment]
Just a wild guess here since I know nothing about Java, but maybe this line:

`case "depth_meter" -> { if (!Config.getBool(ConfigValues.DEPTH_METER)) toRemove.add(identifier); }`

Should be:

`case "depth_meter" -> { if (!Config.getBool(ConfigValues.DEPTH_METER, "enabled")) toRemove.add(identifier); }`

In https://github.com/Additional-Mods/additionaladditions/blob/0ec9101255aa27e281c63247f531e8521dead981/src/main/java/dqu/additionaladditions/mixin/RecipeManagerMixin.java#L32

**Comment by Dqu1J** [comment]
Thanks a lot for reporting that!

**Comment by kxkxrxtx** [comment]
Suposedly it is fixed, but I can't craft the depth meter yet...

**Comment by Dqu1J** [comment]
@kxkxrxtx  Can you send your config & additional additions version & minecraft version & latest log?

**Comment by kxkxrxtx** [comment]
Sure! It's all played on Minecraft 1.19 with Fabric Loader 0.14.8
AA version is 5.0.1. Here are the latest.log and the config in txt format:

[latest.log](https://github.com/Additional-Mods/additionaladditions/files/9295743/latest.log)
[additional-additions-config.txt](https://github.com/Additional-Mods/additionaladditions/files/9295751/additional-additions-config.txt)

**Comment by Dqu1J** [comment]
Please update ADAD to 5.0.2, it was fixed in 5.0.2. @kxkxrxtx

**Comment by ShiroYatagami** [comment]
> Just a wild guess here since I know nothing about Java, but maybe this line:
> 
> `case "depth_meter" -> { if (!Config.getBool(ConfigValues.DEPTH_METER)) toRemove.add(identifier); }`
> 
> Should be:
> 
> `case "depth_meter" -> { if (!Config.getBool(ConfigValues.DEPTH_METER, "enabled")) toRemove.add(identifier); }`
> 
> In
> 
> https://github.com/Additional-Mods/additionaladditions/blob/0ec9101255aa27e281c63247f531e8521dead981/src/main/java/dqu/additionaladditions/mixin/RecipeManagerMixin.java#L32

This actually does fix the problem as I just tested it, all I had to do was add the` , "enabled" ` part and build the mod and it fixed the problem
