### ISSUE TITLE
[1.19.1] Issue loading alongside Corail Recycler

### ISSUE THREAD

**Issue by Baggytrousers27** [Additional-Mods/additionaladditions#79]
Forge 42.0.0+
additionaladditions-5.0.1d
corail_recycler-5.6.0-1.1

The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Corail Recycler (corail_recycler) encountered an error during the common_setup event phase

[crashlog](https://github.com/Additional-Mods/additionaladditions/files/9225449/crash-2022-07-30_15.56.42-client.txt)

Submitted an issue on Corail's side as well.

**Comment by Dqu1J** [comment]
1.19.1 is not yet supported
