### ISSUE TITLE
[Fabric v4.0.4] Honeyed Apple and Fried Egg not being disabled when disabled in config.

### ISSUE THREAD

**Issue by IGoOofALot14** [Additional-Mods/additionaladditions#81]
When I edited the config file to remove honeyed apple and fried egg, they still appeared when I reopened Minecraft. The strange thing about that is that when I something else, it got disabled. It looks like it's a problem with just the food items. Another thing to note is that when I attempt to use the settings through Mod Menu to disable the items, all of the food items do not appear. I tested deleting the configuration file and allowing it to regenerate it before changing it, along with using the mod without any other mods (besides Fabric API) to the same result.

**Comment by Dqu1J** [comment]
config file? are you able to craft those items?

**Comment by IGoOofALot14** [comment]
The config file I was referring to is the "additional-additions-config.json" file in the config folder. When I opened the game, the recipes were still available but are not craftable. That's really weird, when I filed the report they were still craftable. I guess whatever the problem, its fixed now. Sorry for wasting your time, keep up the good work your mod is one of my favorite mods!

**Comment by Dqu1J** [comment]
Ty!
