### ISSUE TITLE
Spyglass crossbow always crashes game when press shift to use.

### ISSUE THREAD

**Issue by Mahadbaloch** [Additional-Mods/additionaladditions#82]
Crash report:
[crash-2022-08-14_18.25.16-client.txt](https://github.com/Additional-Mods/additionaladditions/files/9333441/crash-2022-08-14_18.25.16-client.txt)

**Comment by Dqu1J** [comment]
Are you able to reproduce this with only fabric api and additional additions installed? I'm not sure if it does relate to adad, maybe it's a compat issue

**Comment by pointwoods** [comment]
Might be an issue w malilib, architectury, iceberg, or kotlin. I've been having a similar issue and those seem to be the only mods we have in common

**Comment by Dqu1J** [comment]
can't reproduce with adad, malilib, iceberg and kotlin on 1.19.2 fabric

**Comment by pointwoods** [comment]
Both this person and I are running 1.19, not 1.19.2, so that might be the issue. It's also possible that I missed a mod when reading through the crash log.

**Comment by Dqu1J** [comment]
1.19 isn't currently supported, so i'm testing on 1.19.2

**Comment by Mahadbaloch** [comment]
Yeah im on 1.19

**Comment by Dqu1J** [comment]
cant reproduce
