### ISSUE TITLE
[Bug] When installed with a large modpack on a velocity-accessed Fabric server, other servers have screwed up textures.

### ISSUE THREAD

**Issue by purejosh** [Additional-Mods/additionaladditions#86]
Unknown if this is something you're able to control, but when I have additional additions installed on my fabric server/client, and I log in to the velocity server's hub (Velocity proxy + 8 Paper servers + 1 Fabric server), all the blocks are random as hell and I'm unsure why. It could be that I'm exceeding a block ID limit and blocks are being transposed up in count, but I figured I'd report it. 

Without installed: 
![2022-09-07_10 05 10 (Large)](https://user-images.githubusercontent.com/70633949/188927552-b7aa2bf2-2110-43a4-91d7-78cdebb00525.png)

With installed: 
![2022-09-07_10 03 29 (Large)](https://user-images.githubusercontent.com/70633949/188927583-158b3b91-07ca-477b-83f2-9fe79a4aea1c.png)

**Comment by Dqu1J** [comment]
not an issue on our end, check if there are any mod mismatches between client/server, try asking in velocity/fabric support servers

**Comment by purejosh** [comment]
I mean, I literally just said that they don't match. This means that your mod doesn't support proxy servers, since proxy server lobbies don't include the mods that are on the modded servers. It also sounds like you don't have an interest in understanding the issue, either, which is disappointing.

**Comment by Dqu1J** [comment]
that's not something i can fix afaik

**Comment by UnperishedDev** [comment]
I have the same issue, only with this mod. Quite annoying really, as I can't use this mod in my modpack anymore because of this reason. Hopefully, (even though this is marked as not planned) this can be fixed in the future.
