### ISSUE TITLE
Mod ignoring its own config file [1.19.2]

### ISSUE THREAD

**Issue by lxly9** [Additional-Mods/additionaladditions#89]
The mod is basically just ignoring its own config file, so it doesn't let you disable anything. I've disabled gilded netherite and rose golden tools but they still show up as craftable, in the creative inventory and in emi.

**Comment by Dqu1J** [comment]
Items aren’t getting removed entirely, just their crafting recipe is getting disabled. Have you tried actually crafting them?

**Comment by lxly9** [comment]
yup, i did and they still came up. Emi showed their recipes still.

**Comment by Dqu1J** [comment]
Can you please send your config file and your latest log?
