### ISSUE TITLE
Make gilded netherite's fire resistance duration configurable

### ISSUE THREAD

**Issue by Psychodeus** [Additional-Mods/additionaladditions#91]
![image](https://user-images.githubusercontent.com/93028949/196297217-32a24312-d88b-49b1-ae9b-fb275fef2422.png)
I want this inside my mysterious_bundle.json, how to write it? And I want x3 each bundle.

> {
          "type": "minecraft:item",
          "weight": 3,
          "name": "additionaladditions:rope"
    }

**Comment by Psychodeus** [comment]
![image](https://user-images.githubusercontent.com/93028949/196297967-65f6e7d0-fd48-47fb-82e6-ec5f93eb1522.png)
![image](https://user-images.githubusercontent.com/93028949/196297987-91b5a4b5-ae34-4cfa-ae9c-81487f4331a3.png)
And how to config to have the same armor toughness?

**Comment by Psychodeus** [comment]
Wait, what? Fire resistance, I thought it's just to hush piggy away.
![image](https://user-images.githubusercontent.com/93028949/196313745-1954d8ec-a644-4834-b578-840436fb9986.png)
Please tell me how to edit to turn it off, it's too OP.

**Comment by Dqu1J** [comment]
Has been added in 5.2.0!
