### ISSUE TITLE
Additional Additions makes multiplayer virtually unplayable

### ISSUE THREAD

**Issue by xlifi** [Additional-Mods/additionaladditions#92]
With Additional Additions:
![with_addadd](https://user-images.githubusercontent.com/70767436/198926915-aa8a6eea-8048-40cb-9948-6f742f8ecf72.png)
Without Additional Additions:
![no_addadd](https://user-images.githubusercontent.com/70767436/198926910-71a62360-80f8-400c-952b-4dbafef15916.png)

Logs, named respectively:
[with_addadd.log](https://github.com/Additional-Mods/additionaladditions/files/9897872/with_addadd.log)
[no_addadd.log](https://github.com/Additional-Mods/additionaladditions/files/9897870/no_addadd.log)

No idea why it is that way. I did play as normal with Additional Additions for some time, but now this
Why unplayable? Because stone turns into glowberries.
Everything included in logs. Probably. If you need some additional information, I can give it.

**Comment by Mia-Rain** [comment]
I had this happen personally when I added the mod to my server, so I can report this happens, but it went away after a rejoin.

**Comment by Dqu1J** [comment]
@xlifi please confirm: is additional additions installed on the server? is it the same version as on the client?

**Comment by xlifi** [comment]
> @xlifi please confirm: is additional additions installed on the server? is it the same version as on the client?

Additional additions is not installed on the server. Why does it matter?

**Comment by Dqu1J** [comment]
@xlifi it needs to be installed on both the server and the client to work properly.

**Comment by TrulyBoom** [comment]
May I ask what computer you're using. I use a MacBook Pro and I am also experiencing these issues along with two other mods.

**Comment by Dqu1J** [comment]
with the logs you attached here, it looks like its an issue on your end. you joined a vanilla server with a mod which needs to be installed on both the client and the server, what did you expect? addadd needs to be on both sides.

**Comment by xlifi** [comment]
I expected blocks to be shown correctly and playing without additionnal additions features. Still probably was something wrong with my RAM or OS. Also issue persisted when i tried joining modded server which had additional additions

**Comment by Dqu1J** [comment]
@xlifi could you please send logs while joining a server with additional additions installed too? joining incompatible servers in not supported

**Comment by xlifi** [comment]
> @xlifi could you please send logs while joining a server with additional additions installed too? joining incompatible servers in not supported 

no, I can't anymore

**Comment by Dqu1J** [comment]
can't help then. if that issue occurs then that means that the mods on client and the server aren't the same.
