### ISSUE TITLE
[1.18.2] Rose Gold gear is way too OP

### ISSUE THREAD

**Issue by vizthex123** [Additional-Mods/additionaladditions#95]
The tools should have 200 durability, and the armour should have 35 or so less than Iron.

As is, they're basically diet diamond - 900 durability with the same damage.

Or, it should be harder to craft.

Applies to the 1.19 version too.

**Comment by Dqu1J** [comment]
You can change rose gold’s stats yourselfs using datapacks since 4.0

**Comment by vizthex123** [comment]
Well I change it using property modifier, but I think it should be properly balanced in the mod.
